name: CI/CD

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: CI/CD Build
    uses: ./.github/workflows/build.yml

  qa:
    needs: build
    name: CI/CD QA
    uses: ./.github/workflows/qa.yml

  semantic:
    needs: qa
    if: github.event_name != 'pull_request'
    name: CI/CD Semantic
    uses: ./.github/workflows/semantic.yml
    secrets: inherit

  npm-publish:
    needs: semantic
    name: CI/CD Publish
    uses: ./.github/workflows/npm-publish.yml
    secrets: inherit
