name: CI/CD

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
      - 'major/*'

jobs:
#  build:
#    name: 'Stage #1'
#    uses: ./.github/workflows/build.yml

#  qa:
#    needs: build
#    name: 'Stage #2'
#    uses: ./.github/workflows/qa.yml

  semantic:
#    needs: qa
#    if: github.event_name != 'pull_request'
    name: 'Stage #3'
    uses: ./.github/workflows/semantic.yml
    secrets: inherit

#  npm-publish:
#    needs: semantic
#    name: 'Stage #4'
#    uses: ./.github/workflows/npm-publish.yml
#    secrets: inherit
