name: CI/CD

on:
  push:
    branches:
      - 'main'
      - 'rc-*'

jobs:
  build:
    name: Build package
    uses: ./.github/workflows/build.yml

  qa:
    needs: build
    name: QA Tests
    uses: ./.github/workflows/qa.yml

  npm-publish:
    needs: qa
    name: NPM Publish
    uses: ./.github/workflows/npm-publish.yml
    secrets: inherit
