name: 'Stage #3: Node.js Publish Package'

on:
  release:
    types: [created]
  workflow_dispatch:
  workflow_call:

jobs:
  publish-npm:
    name: NPM Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v4
        with:
          path: lib
          key: lib-${{ hashFiles('package.json') }}
          restore-keys: |
            lib-
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: npm ci

      - name: Download hash
        uses: actions/download-artifact@v3
        with:
          name: package-hash

      - name: Check if package.json has changed
        run: |
          echo "Cached hash: $(cat package-hash/hash.txt)"
          echo "Current hash: ${{ hashFiles('package.json') }}"
          if [[ "$(cat package-hash/hash.txt)" != "${{ hashFiles('package.json') }}" ]]; then
            echo "::set-output name=changed::true";
          else
            echo "::set-output name=changed::false";
          fi
        id: hash-check

      - name: Publish package if package.json has changed.
        if: steps.hash-check.outputs.changed == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
