name: 'Stage #3: Node.js Publish Package'

on:
  release:
    types: [created]
  workflow_dispatch:
  workflow_call:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v4
        with:
          path: lib
          key: lib-${{ hashFiles('package.json') }}
          restore-keys: |
            lib-
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: npm ci
      - run: npm adduser
      - run: npm publish --provenance --access public
      - run: |
          echo "NPM TOKEN: ${{secrets.NPM_TOKEN}}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
