name: 'Stage #2: QA Tests'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  qa:
    name: QA Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache lib packages
      uses: actions/cache@v4
      with:
        path: lib
        key: lib-${{ hashFiles('package.json') }}
        restore-keys: |
          lib-

    - run: npm ci
    - run: npm test
    - run: npm run lint

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
