name: 'Stage #3: Semantic Release'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
      - run: npm run build

      - name: Create release and publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Get new version from package.json
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Print new version
        run: echo $VERSION

      - name: Create Artifact with version
        run: echo $VERSION > version.txt

      - name: Upload version as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-artifact
          path: version.txt
